[tool.poetry]
name = "pulseframeproductions"
version = "0.1.0"
description = ""
authors = ["Sam Lim <sam@typhonic.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
